function buildBook({
  id,
  title,
  author,
  isbn,
  category,
  rfid,
  copyCode,
  course,
  discipline,
  location,
  row,
  shelf,
  copies = 1,
  available,
  cover,
  createdAt,
  updatedAt,
}) {
  return {
    id,
    title,
    author,
    isbn: isbn || null,
    category: category || 'Geral',
    rfid: rfid || '',
    copyCode: copyCode || '',
    course: course || '',
    discipline: discipline || '',
    location: location || '',
    row: row || '',
    shelf: shelf || '',
    copies,
    available: available ?? copies,
    cover: cover || null,
    createdAt: createdAt || new Date().toISOString(),
    updatedAt: updatedAt || new Date().toISOString(),
  };
}

module.exports = { buildBook };
